package com.generalgivers.foundation.service;

import com.generalgivers.foundation.entity.User;
import com.generalgivers.foundation.entity.UserRole;
import com.generalgivers.foundation.repository.UserRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.util.List;

@Slf4j
@Service
@RequiredArgsConstructor
public class ReportNotificationService {

    private final UserRepository userRepository;
    private final MailerSendService mailerSendService;

    public void notifyReportGenerated(String reportType, String generatorName) {
        try {
            // Get admin and leadership users for report notifications
            List<User> adminUsers = userRepository.findByRoleInAndIsActiveTrue(
                List.of(UserRole.SUPER_USER, UserRole.CHAIRPERSON, 
                       UserRole.SECRETARY_GENERAL, UserRole.TREASURER)
            );

            String subject = "Report Generated - " + reportType;
            String content = String.format(
                "A %s report has been generated by %s. " +
                "This report contains current organizational data and analytics.",
                reportType, generatorName
            );

            for (User user : adminUsers) {
                mailerSendService.sendNotificationEmail(
                    user.getEmail(),
                    user.getName(),
                    subject,
                    content
                );
            }

            log.info("Report generated notifications sent to {} admin users", adminUsers.size());
        } catch (Exception e) {
            log.error("Failed to send report generated notifications", e);
        }
    }

    public void notifyDataExport(String exportType, String exporterName, int recordCount) {
        try {
            // Get admin users for data export notifications
            List<User> adminUsers = userRepository.findByRoleInAndIsActiveTrue(
                List.of(UserRole.SUPER_USER, UserRole.CHAIRPERSON)
            );

            String subject = "Data Export - " + exportType;
            String content = String.format(
                "Data export (%s) has been performed by %s. " +
                "Export contained %d records. This action has been logged for audit purposes.",
                exportType, exporterName, recordCount
            );

            for (User user : adminUsers) {
                mailerSendService.sendNotificationEmail(
                    user.getEmail(),
                    user.getName(),
                    subject,
                    content
                );
            }

            log.info("Data export notifications sent to {} admin users", adminUsers.size());
        } catch (Exception e) {
            log.error("Failed to send data export notifications", e);
        }
    }
}