package com.generalgivers.foundation.entity;

public enum NotificationType {
    DONATION_RECEIVED,
    DONATION_COMPLETED,
    DONATION_FAILED,
    PROJECT_CREATED,
    PROJECT_UPDATED,
    PROJECT_COMPLETED,
    PROJECT_DELETED,
    VISIT_SCHEDULED,
    VISIT_COMPLETED,
    USER_REGISTERED,
    SYSTEM_ALERT
}
